"""Fixed TrialAgentBench v1 values required by independent verification."""

from __future__ import annotations

from typing import Final

RELEASE_RECOVERY_ABSOLUTE_TOLERANCE_V1: Final = 1e-4
TRIALEVAL_DESIGN_PROFILE_COUNT_V1: Final = 7
TRIALEVAL_EVALUATION_SERIES_COUNT_V1: Final = 9
TRIALEVAL_REGIME_CELL_COUNT_V1: Final = 25
TRIALEVAL_ROUTE_ARCHETYPE_COUNT_V1: Final = 17
TRIALEVAL_CONTEXT_COUNT_V1: Final = 5
TRIALEVAL_BASE_TRIAL_REPLICATES_PER_CELL_V1: Final = 4
TRIALEVAL_BASE_TRIAL_COUNT_V1: Final = (
    TRIALEVAL_REGIME_CELL_COUNT_V1 * TRIALEVAL_BASE_TRIAL_REPLICATES_PER_CELL_V1
)
TRIALEVAL_ITEM_COUNT_V1: Final = (
    TRIALEVAL_BASE_TRIAL_COUNT_V1 * TRIALEVAL_CONTEXT_COUNT_V1
)
TRIALEVAL_C5_REFERENCE_COUNT_V1: Final = TRIALEVAL_BASE_TRIAL_COUNT_V1
TRIALEVAL_PARTIAL_IDENTIFICATION_DELTA_GRID_V1: Final = (0.05, 0.10, 0.20)
TRIALEVAL_VALIDATED_ENDPOINT_BOOTSTRAP_REPLICATES_V1: Final = 1_000
TRIALEVAL_VALIDATED_ENDPOINT_MINIMUM_CONVERGED_BOOTSTRAPS_V1: Final = 950
TRIALEVAL_VALIDATED_ENDPOINT_BOOTSTRAP_SEED_V1: Final = 2_606
TRIALEVAL_VALIDATED_ENDPOINT_MINIMUM_CLASSIFICATION_PROBABILITY_V1: Final = 0.55
TRIALEVAL_VALIDATED_ENDPOINT_MAXIMUM_CLASSIFICATION_PROBABILITY_V1: Final = 0.995
TRIALEVAL_VALIDATED_ENDPOINT_PROBABILITY_CLIP_V1: Final = 1e-6
TRIALEVAL_VALIDATED_ENDPOINT_OPTIMIZER_GRADIENT_TOLERANCE_V1: Final = 1e-9
TRIALEVAL_VALIDATED_ENDPOINT_OPTIMIZER_MAXIMUM_ITERATIONS_V1: Final = 2_000
TRIALEVAL_VALIDATED_ENDPOINT_OPTIMIZER_MAXIMUM_LINE_SEARCH_STEPS_V1: Final = 50
TRIALEVAL_VALIDATED_ENDPOINT_CELL_COLUMNS_V1: Final = (
    "treatment_arm",
    "prognostic_stratum",
    "observed_event",
    "validation_selected",
    "validated_event",
)
TRIALEVAL_STANDARDIZED_RISK_BASELINE_COVARIATES_V1: Final = (
    "AGE",
    "BMI",
    "HX_HTN",
    "HX_DM2",
    "HX_CKD",
)
TRIALDEV_SCENARIO_COUNT_V1: Final = 50
TRIALDEV_REPLAY_CALIBRATION_TOLERANCE_V1: Final = 1e-10
TRIALDEV_MAX_ACTION_ONLY_SHORTCUT_SUPPORT_RATE_V1: Final = 0.50
TRIALDEV_MAX_POINT_ESTIMATE_SHORTCUT_SUPPORT_RATE_V1: Final = 0.75

__all__ = [
    "RELEASE_RECOVERY_ABSOLUTE_TOLERANCE_V1",
    "TRIALDEV_REPLAY_CALIBRATION_TOLERANCE_V1",
    "TRIALDEV_MAX_ACTION_ONLY_SHORTCUT_SUPPORT_RATE_V1",
    "TRIALDEV_MAX_POINT_ESTIMATE_SHORTCUT_SUPPORT_RATE_V1",
    "TRIALDEV_SCENARIO_COUNT_V1",
    "TRIALEVAL_BASE_TRIAL_COUNT_V1",
    "TRIALEVAL_BASE_TRIAL_REPLICATES_PER_CELL_V1",
    "TRIALEVAL_C5_REFERENCE_COUNT_V1",
    "TRIALEVAL_CONTEXT_COUNT_V1",
    "TRIALEVAL_DESIGN_PROFILE_COUNT_V1",
    "TRIALEVAL_EVALUATION_SERIES_COUNT_V1",
    "TRIALEVAL_ITEM_COUNT_V1",
    "TRIALEVAL_PARTIAL_IDENTIFICATION_DELTA_GRID_V1",
    "TRIALEVAL_REGIME_CELL_COUNT_V1",
    "TRIALEVAL_ROUTE_ARCHETYPE_COUNT_V1",
    "TRIALEVAL_STANDARDIZED_RISK_BASELINE_COVARIATES_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_BOOTSTRAP_REPLICATES_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_BOOTSTRAP_SEED_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_CELL_COLUMNS_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_MAXIMUM_CLASSIFICATION_PROBABILITY_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_MINIMUM_CLASSIFICATION_PROBABILITY_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_MINIMUM_CONVERGED_BOOTSTRAPS_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_OPTIMIZER_GRADIENT_TOLERANCE_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_OPTIMIZER_MAXIMUM_ITERATIONS_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_OPTIMIZER_MAXIMUM_LINE_SEARCH_STEPS_V1",
    "TRIALEVAL_VALIDATED_ENDPOINT_PROBABILITY_CLIP_V1",
]
