"""Numerical boundary constants shared by public benchmark evaluation."""

from __future__ import annotations

from typing import Final

FLOAT_EQUALITY_ABS_TOLERANCE_V1: Final = 1e-12
MINIMUM_TWO_SIDED_CONFIDENCE_LEVEL_V1: Final = 0.5
PUBLICATION_BOOTSTRAP_REPLICATES_V1: Final = 10_000
PUBLICATION_CONFIDENCE_LEVEL_V1: Final = 0.95
SHA256_HEX_DIGEST_LENGTH: Final = 64
TRIALDEV_CHECKPOINT_ANALYSIS_SEED_V1: Final = 20_260_724
TRIALDEV_OBSERVATIONAL_ANALYSIS_SEED_V1: Final = 20_260_720
TRIALDEV_RANDOMIZED_ARM_COUNT_V1: Final = 2
TRIALEVAL_ANALYSIS_SPECIFICATION_SEED_OFFSET_V1: Final = 200_000
TRIALEVAL_FACTORIAL_ARM_SEED_OFFSET_V1: Final = 500_000
TRIALEVAL_OBSERVABLE_SEED_OFFSET_V1: Final = 10_000
TRIALEVAL_TARGETED_CONTROL_SEED_OFFSET_V1: Final = 100_000

__all__ = [
    "FLOAT_EQUALITY_ABS_TOLERANCE_V1",
    "MINIMUM_TWO_SIDED_CONFIDENCE_LEVEL_V1",
    "PUBLICATION_BOOTSTRAP_REPLICATES_V1",
    "PUBLICATION_CONFIDENCE_LEVEL_V1",
    "SHA256_HEX_DIGEST_LENGTH",
    "TRIALDEV_CHECKPOINT_ANALYSIS_SEED_V1",
    "TRIALDEV_OBSERVATIONAL_ANALYSIS_SEED_V1",
    "TRIALDEV_RANDOMIZED_ARM_COUNT_V1",
    "TRIALEVAL_ANALYSIS_SPECIFICATION_SEED_OFFSET_V1",
    "TRIALEVAL_FACTORIAL_ARM_SEED_OFFSET_V1",
    "TRIALEVAL_OBSERVABLE_SEED_OFFSET_V1",
    "TRIALEVAL_TARGETED_CONTROL_SEED_OFFSET_V1",
]
